In [2]:
import numpy as np
import numpy.random as np_random

## Repeat: 按元素

In [3]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [4]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [5]:
arr.repeat([2, 3, 4]) # 3个元素，分别复制2, 3, 4次。长度要匹配！

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

## Repeat，指定轴

In [7]:
arr = np_random.randn(2, 2)
arr

array([[ 0.42997078,  0.47043017],
       [ 0.22418447, -2.28328463]])

In [8]:
arr.repeat(2, axis = 0) # 按行repeat

array([[ 0.42997078,  0.47043017],
       [ 0.42997078,  0.47043017],
       [ 0.22418447, -2.28328463],
       [ 0.22418447, -2.28328463]])

In [9]:
arr.repeat(2, axis = 1) # 按列repeat

array([[ 0.42997078,  0.42997078,  0.47043017,  0.47043017],
       [ 0.22418447,  0.22418447, -2.28328463, -2.28328463]])

In [10]:
arr.repeat(2, axis = 0) # 按行repeat

array([[ 0.42997078,  0.47043017],
       [ 0.42997078,  0.47043017],
       [ 0.22418447, -2.28328463],
       [ 0.22418447, -2.28328463]])

## Tile: 参考贴瓷砖

In [12]:
np.tile(arr, 2)

array([[ 0.42997078,  0.47043017,  0.42997078,  0.47043017],
       [ 0.22418447, -2.28328463,  0.22418447, -2.28328463]])

In [13]:
np.tile(arr, (2, 3))  # 指定每个轴的tile次数

array([[ 0.42997078,  0.47043017,  0.42997078,  0.47043017,  0.42997078,
         0.47043017],
       [ 0.22418447, -2.28328463,  0.22418447, -2.28328463,  0.22418447,
        -2.28328463],
       [ 0.42997078,  0.47043017,  0.42997078,  0.47043017,  0.42997078,
         0.47043017],
       [ 0.22418447, -2.28328463,  0.22418447, -2.28328463,  0.22418447,
        -2.28328463]])

## 将一维数组转换为二维数组

In [14]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
arr.reshape((4, 2)).reshape((2, 4)) # 支持链式操作

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# 维度大小自动推导

In [18]:
arr = np.arange(15)

In [19]:
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## 获取维度信息并应用

In [20]:
other_arr = np.ones((3, 5))
other_arr

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [21]:
other_arr.shape

(3, 5)

In [22]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 高维数组拉平

In [23]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
arr.ravel() #array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Fancy Indexing例子代码

In [25]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

# 使用take

In [26]:
arr.take(inds)

array([700, 100, 200, 600])

# 使用put更新内容

In [27]:
arr.put(inds, 50)
arr

array([  0,  50,  50, 300, 400, 500,  50,  50, 800, 900])

In [28]:
arr.put(inds, [70, 10, 20, 60])
arr

array([  0,  10,  20, 300, 400, 500,  60,  70, 800, 900])

# 连接两个二维数组

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.concatenate([arr1, arr2], axis = 0)  # 按行连接

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([arr1, arr2], axis = 1)  # 按列连接

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 所谓堆叠，参考叠盘子。。。连接的另一种表述

In [33]:
np.vstack((arr1, arr2)) # 垂直堆叠

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.hstack((arr1, arr2)) # 水平堆叠

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# 拆分数组

In [36]:
arr = np_random.randn(5, 5)
arr

array([[ 1.03579156, -0.05656742, -1.49395411,  0.08641157,  0.48999649],
       [-0.01534615,  0.01580376, -1.15758293,  0.59694694,  1.04052225],
       [-0.30921706, -0.89386129,  0.61382494, -0.88366197,  0.7020562 ],
       [-0.42815277, -0.65708321, -0.2294041 ,  0.08873267,  1.35051924],
       [-0.25830531, -0.11425392,  0.47094797, -0.96252402, -0.82313002]])

# 水平拆分

In [37]:
first, second, third = np.split(arr, [1, 3], axis = 0)

In [38]:
first

array([[ 1.03579156, -0.05656742, -1.49395411,  0.08641157,  0.48999649]])

In [39]:
second

array([[-0.01534615,  0.01580376, -1.15758293,  0.59694694,  1.04052225],
       [-0.30921706, -0.89386129,  0.61382494, -0.88366197,  0.7020562 ]])

In [40]:
third

array([[-0.42815277, -0.65708321, -0.2294041 ,  0.08873267,  1.35051924],
       [-0.25830531, -0.11425392,  0.47094797, -0.96252402, -0.82313002]])

In [41]:
first, second, third = np.split(arr, [1, 3], axis = 1)

In [42]:
first

array([[ 1.03579156],
       [-0.01534615],
       [-0.30921706],
       [-0.42815277],
       [-0.25830531]])

In [43]:
second

array([[-0.05656742, -1.49395411],
       [ 0.01580376, -1.15758293],
       [-0.89386129,  0.61382494],
       [-0.65708321, -0.2294041 ],
       [-0.11425392,  0.47094797]])

In [44]:
third

array([[ 0.08641157,  0.48999649],
       [ 0.59694694,  1.04052225],
       [-0.88366197,  0.7020562 ],
       [ 0.08873267,  1.35051924],
       [-0.96252402, -0.82313002]])

# 堆叠辅助类

In [45]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np_random.randn(3, 2)

# r_用于按行堆叠

In [46]:
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.71152192,  0.92984246],
       [ 1.2884566 , -0.88613191],
       [ 0.99229755, -0.4926519 ]])

# c_用于按列堆叠

In [47]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.71152192,  0.92984246,  3.        ],
       [ 1.2884566 , -0.88613191,  4.        ],
       [ 0.99229755, -0.4926519 ,  5.        ]])

# 切片直接转为数组

In [48]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])