In [2]:
import numpy as np

# 读取csv文件做为数组

In [3]:
arr = np.loadtxt('array_ex.txt', delimiter = ',')
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

# 数组文件读写

In [4]:
arr = np.arange(10)
np.save('some_array', arr)

In [5]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 多个数组压缩存储

In [6]:
np.savez('array_archive.npz', a = arr, b = arr)

In [7]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])